### ISSUE TITLE
multiple batches

### ISSUE THREAD

**Issue by chintanparekh2301** [yycunc/SMNN#2]
Hi
How does one enter cell cluster information for multiple batches . The current command line only has batch1 and batch 2 clusters as options. I would like to correct three batches (one will be the reference and the other batches need to be corrected). I have cell culster information for each of the batches. I can input expression matrices for multiple batches but there seems to be no way for entering the cluster information vectors for three btaches
Thank you very much

**Comment by yycunc** [comment]
Hi 
Thanks for pointing this error out, and sorry for my late response. I have fixed this error and now it can deal with more than two batches. The new SMNN version has been updated on github. You can reinstall the SMNN package and follow the pipeline to correct the batch effect among multiple datasets. 

Please let me know if there is any other question.

Thanks again for using our method and pointing out the error!
